package com.server.app.constants;

public final class ApplicationConstants {
    private ApplicationConstants() {
        throw new AssertionError("Initialization of this class is not allowed");
    }

    public static final int DEFAULT_RESPONSE_CODE = 200;
    public static final long DEFAULT_RESPONSE_LENGTH = 0L;
    public static final int METHOD_NOT_ALLOWED_HTTP_CODE = 405;
    public static final String EMPTY_STRING = "";
    public static final String EMPTY_SPACE = " ";
    public static final String EQUALS_CHAR = "=";
    public static final String UNDERSCORE = "_";
    public static final String HYPHEN = "-";
    public static final String COMMA = ",";
    public static final String SEMI_COLON = ";";
    public static final String COLON = ":";
    public static final String DEFAULT_PATH = "/";
    public static final String AMPERSAND_CHAR = "&";
    public static final String QUERY_CHAR = "?";
    public static final String SQL_COMMENT = "--";
    public static final String SQL_QUERY = "(?)";
    public static final String BLOCK_COMMENT_START = "/*";
    public static final String BLOCK_COMMENT_END = "*/";
    public static final String SEPARATOR = "\\|~\\|~\\|";
    public static final String SPLIT_URL_AND_QUERY_PARAM_REGEX = "\\?(?!\\?)";
    public static final String LOCALHOST_1 = "127.0.0.1";
    public static final String LOCALHOST_2 = "0.0.0.0";
    public static final String CHARSET_UTF8 = "charset=UTF-8";
    public static final String SECURE_RANDOM_ALGORITHM = "SHA1PRNG";
    public static final String SQL_DDL_QUERY_FILE_PATH = "/data/queries/ddl.sql";
    public static final String SQL_PRAGMA_ENABLE_FOREIGN_KEY_QUERY = "PRAGMA foreign_keys = ON";
    public static final String HTTP_SCHEME = "http";
    public static final String HTTPS_SCHEME = "https";
    public static final String LOCALHOST = "localhost";
    public static final String COOKIE_HEADER_KEY = "set-cookie";
    public static final String DOMAIN = "Domain";
    public static final String EXPIRES = "Expires";
    public static final String HTTPONLY = "HttpOnly";
    public static final String MAX_AGE = "Max-Age";
    public static final String PARTITIONED = "Partitioned";
    public static final String PATH = "Path";
    public static final String SAME_SITE = "SameSite";
    public static final String SECURE = "Secure";
    public static final String JSON_FILE_EXTENSION = "json";
    public static final String MILLIS_SHORT_FORM = "ms";
    public static final String SPLASH_SCREEN_TITLE = "Starting Mock Server....";
    public static final String APP_TITLE = "Mock Server";
    public static final String APP_PROMPT_MESSAGE_TITLE = "Information";
    public static final String APP_HEADER_FORM_TITLE = "Add Header";
    public static final String APP_EXPORT_COLLECTION_TITLE = "Export Collection";
    public static final String APP_IMPORT_COLLECTION_TITLE = "Import Collection";
    public static final String APP_SETTING_TITLE = "Settings";
    public static final String APP_COOKIE_FORM_TITLE = "Add Cookie";
    public static final String APP_COLLECTION_FORM_TITLE = "Add Collection";
    public static final String EDIT_COLLECTION_FORM_TITLE = "Edit Collection";
    public static final String APP_SERVER_FORM_TITLE = "Create Mock Server";
    public static final String APP_SERVER_FORM_EDIT_TITLE = "Edit Mock Server";
    public static final String APP_SERVER_FORM_SAVE_BUTTON = "Create Server";
    public static final String APP_SERVER_FORM_EDIT_BUTTON = "Update Server";
    public static final String DIRECTORY_SELECTOR_TITLE = "Select directory to export collections";
    public static final String FILE_SELECTOR_TITLE = "Select collection file to import";
    public static final String ACTIVE_SERVER_MANAGER_TITLE = "Active Server Manager";
    public static final String SET_SERVER_STATUS_ACTIVE_BUTTON_TEXT = "Stop";
    public static final String SET_SERVER_STATUS_INACTIVE_BUTTON_TEXT = "Start";
    public static final String EXPORT_DIRECTORY_PATH_DEFAULT_TEXT = "Path: ";
    public static final String IMPORT_FILE_PATH_DEFAULT_TEXT = "File Name: ";
    public static final String TRACER = "tracer";
    public static final String ACTIVE = "ACTIVE";
    public static final String INACTIVE = "INACTIVE";
    public static final String JAVA_CROSS_PLATFORM_USER_DIRECTORY_PATH = System.getProperty("user.home");
    public static final String LIGHT_GREY_COLOR_HEX_CODE = "#e3e3e3;";
    public static final String LIGHT_RED_COLOR_HEX_CODE = "#fcc6c2;";
    public static final String LIGHT_GREEN_COLOR_HEX_CODE = "#cafadb;";
    public static final String DELETE_BUTTON_IMAGE_PATH = "/static/icons/delete-24.png";
}
