
MOCKSERVER_JARSIGN_KEYSTORE=mockserver.jks
MOCKSERVER_JARSIGN_ALIAS=mockserver
MOCKSERVER_JARSIGN_STOREPASS=change_me

MOCKSERVER_CODESIGN_PFX=certificate.pfx
MOCKSERVER_CODESIGN_PFX_PASSWORD=change_me
